import { optimizeAssets, optimizeHome, compressOutput } from './optimize.mjs';
import { readFile, writeFile, mkdir, cp, rm } from 'node:fs/promises';
import * as t from './.build/templates.js';
import {services,projects,posts,industries} from './.build/catalog.js';
const pages=[];
const add=(path,title,family,body)=>pages.push({path,title,family,body});
add('/services/','Servicios','Servicios',t.serviceIndex());
for(const s of services)add(s.href,s.title,'Servicios',t.serviceDetail(s.title,s.visual));
add('/about/','Nosotros','Empresa',t.about());
add('/equipo/','Equipo','Empresa',t.team());
add('/metodologia/','Metodología','Empresa',t.methodology());
add('/proyectos/','Proyectos','Proyectos',t.projectIndex());
for(const p of projects)add(p.href,p.title,'Proyectos',t.projectDetail(p));
add('/industrias/','Industrias','Industrias',t.industryIndex());
for(const i of industries.slice(0,2))add(i.href,i.title,'Industrias',t.serviceDetail(i.title,i.visual,'INDUSTRIAS'));
add('/blog/','Blog','Editorial',t.blogIndex());
for(const p of posts)add(p.href,p.title,'Editorial',t.article(p));
add('/contact/','Contacto','Contacto y acceso',t.contact());
add('/diagnostico/','Diagnóstico','Contacto y acceso',t.diagnostic());
add('/login/','Acceso de clientes','Contacto y acceso',t.auth());
add('/reset-password/','Recuperar acceso','Contacto y acceso',t.auth(true));
for(const [path,title] of [['aviso-de-privacidad','Aviso de privacidad'],['terminos-de-servicio','Términos de servicio'],['data-deletion','Eliminación de datos']])add('/'+path+'/',title,'Información',t.legal(title));
const xml=await readFile('docs/sitemap-observed.xml','utf8');
const livePaths=[...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map(m=>new URL(m[1]).pathname.replace(/\/$/,'')+'/');
const cityNames={'puerto-vallarta':'Puerto Vallarta','bahia-de-banderas':'Bahía de Banderas','guadalajara':'Guadalajara','zapopan':'Zapopan'};
const local=[];
for(const path of livePaths){
 if(path==='/'||pages.some(p=>p.path===path))continue;
 const slug=path.slice(1,-1);
 let title=slug.replaceAll('-',' ');title=title.charAt(0).toUpperCase()+title.slice(1);
 let city='';for(const [s,n] of Object.entries(cityNames))if(slug.endsWith(s)){city=n;title=title.slice(0,-s.length)+'en '+n;}
 const family=/^(desarrollo-web|automatizacion|consultoria)-/.test(slug)&&city?'Presencia local':'Guías y soluciones';
 if(slug.startsWith('desarrollo-web-'))title='Desarrollo web en '+city;
 if(slug.startsWith('automatizacion-')&&!slug.includes('mensajes'))title='Automatización en '+city;
 if(slug.startsWith('consultoria-'))title='Consultoría en '+city;
 const visual=/whatsapp/.test(slug)?'chat':/automatiza/.test(slug)?'orbit':/consultoria/.test(slug)?'grid':'web';
 add(path,title,family,t.serviceDetail(title,visual,city?'PRESENCIA LOCAL / '+city:'GUÍAS Y SOLUCIONES'));
 local.push(pages.at(-1));
}
add('/guias-transformacion/','Guías y presencia local','Empresa',t.directory(local));
add('/404/','Página no encontrada','Sistema',t.notFound());
const entries=[{path:'/',title:'Inicio · diseño original de Miguel',family:'Inicio'},...pages.map(({path,title,family})=>({path,title,family}))];
add('/mapa/','Mapa del diseño','Sistema',t.directory(entries,true));
await rm('dist',{recursive:true,force:true});await mkdir('dist',{recursive:true});await cp('public','dist',{recursive:true});
await cp('.build/client.js','dist/client.js');
await cp('.build/motion.js','dist/motion.js');
await optimizeAssets();
await writeFile('dist/favicon.svg',t.logo.replace('<svg ','<svg xmlns="http://www.w3.org/2000/svg" '));
for(const page of pages){const dir='dist'+page.path;await mkdir(dir,{recursive:true});await writeFile(dir+'index.html',t.document(page));}
await writeFile('dist/404.html',t.document(pages.find(p=>p.path==='/404/')));
await writeFile('dist/robots.txt','User-agent: *\nDisallow: /\n');
await writeFile('dist/routes.json',JSON.stringify(entries,null,2));
let home=await readFile('src/home.dc.html','utf8');
home=home.replace('<html>','<html lang="es">').replace('<head>','<head>\n<title>PixelTEC · Inicio</title>\n<meta name="robots" content="noindex,nofollow"><link rel="icon" href="/favicon.svg">');
home=home.replace(/<a\b[^>]*>[\s\S]*?<\/a>/g,a=>{
 const text=a.replace(/<[^>]*>/g,'').trim();
 let href=null;
 if(/Industrias/.test(text))href='/industrias/';
 else if(/^Iniciar diagnóstico|^Comenzar/.test(text))href='/diagnostico/';
 else if(/Ver todos los servicios/.test(text))href='/services/';
 else if(/Más sobre nosotros/.test(text))href='/about/';
 else if(text.includes('VER TODOS'))href='/proyectos/';
 else if(/p\.name/.test(text))href='{{ p.href }}';
 else if(/b\.title/.test(text))href='{{ b.href }}';
 else if(/^Servicios\.?$/.test(text))href='/services/';
 else if(/^Proyectos\.?$/.test(text))href='/proyectos/';
 else if(/^Nosotros\.?$/.test(text))href='/about/';
 else if(/^Blog\.?$/.test(text))href='/blog/';
 else if(/^Contacto\.?$|^Hablemos$|^Hablar con/.test(text))href='/contact/';
 else if(text==='Aviso de Privacidad')href='/aviso-de-privacidad/';
 else if(text==='Automatización con IA')href='/services/automatizacion/';
 else if(text==='Desarrollo Web &amp; Apps')href='/services/ecosistemas-web/';
 else if(text==='WhatsApp IA')href='/pixelbot/';
 else if(text==='Consultoría TI'||text==='Soporte TI')href='/services/consultoria/';
 else if(text==='PixelTEC')href='/';
 else if(/FB\.?$|Facebook/.test(text)||a.includes('aria-label="Facebook"'))href='https://www.facebook.com/profile.php?id=61556300117500';
 else if(/IG\.?$|Instagram/.test(text)||a.includes('aria-label="Instagram"'))href='https://instagram.com/pixeltecmx';
 else if(a.includes('href="#"'))href='/contact/';
 return href?a.replace(/href="[^"]*"/,'href="'+href+'"'):a;
});
for(const p of projects)home=home.replaceAll("{ name: '"+p.title+"',","{ href: '"+p.href+"', name: '"+p.title+"',");
let postIndex=0;home=home.replace(/\{ cat: '/g,()=>"{ href: '"+posts[postIndex++ % posts.length].href+"', cat: '");
home=home.replace('{{ sv.t }}</h3>','<a href="{{ sv.href }}" style="color:inherit">{{ sv.t }}</a></h3>');
let serviceIndex=0;home=home.replace(/\{ n: '0[1-4]', t:/g,m=>"{ href: '"+services[serviceIndex++].href+"',"+m.slice(1));
home=home.replace("subLabel: this.state.subbed ? '¡Listo!' : 'Suscribirme'","subLabel: this.state.subbed ? 'Vista previa · sin envío' : 'Suscribirme'");
// Add opt-in motion hooks to the generated copy; preserve the supplied source byte-for-byte.
home=home.replace('</head>','<link rel="stylesheet" href="/motion.css"><script type="module" src="/motion.js"></script></head>').replace('<body>','<body data-pixel-home>');
home=home.replaceAll('<h2 style=', '<h2 data-motion style=');
home=home.replaceAll('<div style="display:grid;grid-template-columns:{{ svcCols }}', '<div data-motion style="display:grid;grid-template-columns:{{ svcCols }}');
home=home.replaceAll('<a href="{{ p.href }}"', '<a data-motion href="{{ p.href }}"');
// Keep the supplied home layout, styles and interactive visuals intact.
home=home.replace('</footer>','<div style="padding:24px clamp(20px,4vw,56px);border-top:1px solid #222;display:flex;flex-wrap:wrap;gap:20px;font-size:13px"><a href="/mapa/">Explorar todas las páginas ↗</a><a href="/equipo/">Equipo</a><a href="/metodologia/">Metodología</a><a href="/guias-transformacion/">Guías y presencia local</a><a href="/login/">Acceso de clientes</a><a href="/terminos-de-servicio/">Términos</a></div></footer>');
await writeFile('dist/index.html',await optimizeHome(home));
await compressOutput();
await writeFile('docs/routes.json',JSON.stringify(entries,null,2));
console.log(`Generadas ${pages.length+1} páginas. Cobertura sitemap: ${livePaths.length}/${livePaths.length}.`);
