import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {parseHTML} from '../../design/landingpagepixel2.0/node_modules/linkedom/esm/index.js';
const origin=process.argv[2]||'https://pixeltec.mx';
const output=process.argv[3]||'/tmp/pixeltec-seo-audit.json';
const catalog=JSON.parse(await readFile(new URL('../../src/components/public-site/generated/pages.json',import.meta.url),'utf8'));
const sitemap=await (await fetch(origin+'/sitemap.xml')).text();
const urls=[...new Set([...sitemap.matchAll(/<loc>(.*?)<\/loc>/g)].map(m=>m[1]).concat('/',...Object.keys(catalog).filter(p=>!p.includes('404'))).map(p=>new URL(p,origin).href))];
const rows=[];let cursor=0;
async function inspect(url){const started=performance.now();const r=await fetch(url,{signal:AbortSignal.timeout(30000)});const html=await r.text();const doc=parseHTML(html).document;const meta=name=>doc.querySelector(`meta[name="${name}"]`)?.getAttribute('content')||null;const nodes=[];const errors=[];for(const s of doc.querySelectorAll('script[type="application/ld+json"]')){try{const obj=JSON.parse(s.textContent);nodes.push(...(Array.isArray(obj)?obj:obj['@graph']||[obj]));}catch(e){errors.push(String(e))}}
return {url,status:r.status,finalUrl:r.url,ms:Math.round(performance.now()-started),bytes:Buffer.byteLength(html),title:doc.querySelector('title')?.textContent,description:meta('description'),robots:meta('robots'),xRobots:r.headers.get('x-robots-tag'),canonical:doc.querySelector('link[rel="canonical"]')?.getAttribute('href'),lang:doc.documentElement.lang,alternates:[...doc.querySelectorAll('link[hreflang]')].map(x=>({lang:x.getAttribute('hreflang'),href:x.getAttribute('href')})),h1:[...doc.querySelectorAll('h1')].map(x=>x.textContent.trim()),headings:[...doc.querySelectorAll('main h1,main h2,main h3,main h4')].map(x=>({level:x.localName,text:x.textContent.trim().slice(0,140)})),schemas:nodes,schemaErrors:errors,images:[...doc.querySelectorAll('img')].map(x=>({src:x.getAttribute('src'),alt:x.getAttribute('alt'),width:x.getAttribute('width'),height:x.getAttribute('height'),loading:x.getAttribute('loading')})),links:[...doc.querySelectorAll('a[href]')].map(x=>x.getAttribute('href')),cache:r.headers.get('cache-control'),encoding:r.headers.get('content-encoding')};}
await Promise.all(Array.from({length:4},async()=>{while(cursor<urls.length){const url=urls[cursor++];try{rows.push(await inspect(url));}catch(e){rows.push({url,error:String(e)})}}}));
const summary={pages:rows.length,errors:rows.filter(x=>x.error||x.status!==200).map(x=>({url:x.url,status:x.status,error:x.error})),missingCanonical:rows.filter(x=>!x.canonical).map(x=>x.url),badH1:rows.filter(x=>x.h1?.length!==1).map(x=>({url:x.url,h1:x.h1})),invalidSchema:rows.filter(x=>x.schemaErrors?.length).map(x=>x.url),noindex:rows.filter(x=>/noindex/.test(x.robots||'')).map(x=>x.url),missingDescription:rows.filter(x=>!x.description).map(x=>x.url)};
await writeFile(output,JSON.stringify({checkedAt:new Date().toISOString(),origin,summary,rows},null,2));console.log(JSON.stringify(summary,null,2));
