import{readFile,writeFile,mkdir,cp}from'node:fs/promises';
import{parseHTML}from'../../design/landingpagepixel2.0/node_modules/linkedom/esm/index.js';
import postcss from'postcss';
const base=new URL('../../',import.meta.url);const source=new URL('design/landingpagepixel2.0/dist/',base);const output=new URL('src/components/public-site/generated/',base);
const routes=JSON.parse(await readFile(new URL('routes.json',source),'utf8'));
const rename=s=>s.replaceAll('/proyectos/','/casos-de-exito/');
const attributes={hreflang:'hrefLang',class:'className',for:'htmlFor',srcset:'srcSet',tabindex:'tabIndex',crossorigin:'crossOrigin',fetchpriority:'fetchPriority',readonly:'readOnly',autofocus:'autoFocus',maxlength:'maxLength','stroke-width':'strokeWidth','stroke-linecap':'strokeLinecap','stroke-linejoin':'strokeLinejoin',viewbox:'viewBox'};
function tree(n){if(n.localName==='a'&&n.closest('footer')&&n.getAttribute('href')?.includes('/pixelbot'))return null;if(n.nodeType===3)return n.textContent;if(n.nodeType!==1||['script','style','noscript','template'].includes(n.localName))return null;const attrs={};for(const a of n.attributes){if(/^on/i.test(a.name))throw Error('Inline event in generated page');if(a.name==='id'&&/^diagnostic.*form$/.test(a.value)){attrs['data-diagnostic-form']=true;continue;}let k=attributes[a.name]??a.name;if(k==='style'){attrs.style={};for(const rule of a.value.split(';')){const i=rule.indexOf(':');if(i<0)continue;let p=rule.slice(0,i).trim();if(!p.startsWith('--'))p=p.replace(/-([a-z])/g,(_,x)=>x.toUpperCase());attrs.style[p]=rule.slice(i+1).trim();}}else attrs[k]=['hidden','disabled','checked','multiple','required','open'].includes(k)?true:rename(a.value);}return{tag:n.localName,attrs,children:[...n.childNodes].map(tree).filter(x=>x!==null)};}
const pages={};let shell;
for(const route of routes){if(route.path==='/'||route.path==='/en/'||/\/(login|reset-password|pixelbot|blog|aviso-de-privacidad|terminos-de-servicio|data-deletion)(\/|$)/.test(route.path))continue;
 const d=parseHTML(await readFile(new URL(route.path.slice(1)+'index.html',source),'utf8')).document;const main=d.querySelector('main');if(!main)continue;main.querySelector('#diagnostic-modal')?.remove();pages[rename(route.path).replace(/\/$/,'')]={title:d.title,schemas:[...d.querySelectorAll('script[type="application/ld+json"]')].map(n=>JSON.parse(rename(n.textContent))),description:d.querySelector('meta[name="description"]')?.getAttribute('content')??'',body:tree(main),noindex:route.path.startsWith('/en/')};
 if(route.path==='/services/'){const footer=d.querySelector('footer');shell={header:tree(d.querySelector('.header-shell')),extras:[...d.body.children].filter(x=>x.tagName!=='MAIN'&&x.tagName!=='HEADER'&&!x.classList.contains('header-shell')&&x!==footer).map(tree).filter(Boolean),footer:tree(footer)};}
}
const hd=parseHTML(await readFile(new URL('index.html',source),'utf8')).document;shell.extras.push(tree(hd.querySelector('#diagnostic-modal')));await writeFile(new URL('home-extras.json',output),JSON.stringify([...hd.querySelectorAll('.project-modal')].map(tree)));
const ehd=parseHTML(await readFile(new URL('en/index.html',source),'utf8')).document;await writeFile(new URL('home-extras-en.json',output),JSON.stringify([...ehd.querySelectorAll('.project-modal')].map(tree)));
await writeFile(new URL('pages.json',output),JSON.stringify(pages));await writeFile(new URL('shell.json',output),JSON.stringify(shell));
const ed=parseHTML(await readFile(new URL('en/services/index.html',source),'utf8')).document;await writeFile(new URL('shell-en.json',output),JSON.stringify({header:tree(ed.querySelector('.header-shell')),footer:tree(ed.querySelector('footer')),extras:[...ed.body.children].filter(x=>x.tagName!=='MAIN'&&x.tagName!=='HEADER'&&!x.classList.contains('header-shell')&&x.tagName!=='FOOTER').map(tree).filter(Boolean).concat(tree(parseHTML(await readFile(new URL('en/index.html',source),'utf8')).document.querySelector('#diagnostic-modal')))}));
// Scope public styles so admin and authentication retain their existing theme.
let css='';for(const file of ['fonts.css','shell.css','content.css','motion.css','service-motion.css','industry-art.css','navigation.css','whatsapp.css','home.css'])css+=await readFile(new URL(file,source),'utf8')+'\n';
const home=parseHTML(await readFile(new URL('index.html',source),'utf8')).document;
const homeCss=[...home.querySelectorAll('style[data-home-rendered]')].map(x=>x.textContent).join('\n');
function scopeCss(source,scope){const ast=postcss.parse(source);ast.walkRules(r=>{if(r.parent.type==='atrule'&&/keyframes$/.test(r.parent.name))return;r.selectors=r.selectors.map(selector=>{let s=selector.replace(/:root/g,scope).replace(/\bbody\b/g,scope).replace(/\bhtml\b/g,scope);s=s.replace(/(?<![\w.-])\[data-pixel-home\]/g,'.public-website[data-pixel-home]');return s.startsWith('.public-website')?s:scope+' '+s;});});return ast.toString();}
await writeFile(new URL('../public.css',output),scopeCss(css,'.public-website')+'\n'+scopeCss(homeCss,'.public-website[data-pixel-home]'));
await cp(new URL('assets/',source),new URL('public/assets/',base),{recursive:true});await cp(new URL('fonts/',source),new URL('public/fonts/',base),{recursive:true});
console.log(Object.keys(pages).length+' page trees compiled, styles scoped, assets copied.');
