type Locale='es'|'en';
const english:Record<string,string>={
  "Constructora": "Construction company",
  "Hotel": "Hotel",
  "Clínica o consultorio": "Clinic or medical practice",
  "Ecommerce": "Ecommerce",
  "Moda y retail": "Fashion and retail",
  "Logística": "Logistics",
  "Distribución de agua": "Water distribution",
  "Energía solar": "Solar energy",
  "Restaurante": "Restaurant",
  "Servicios": "Services",
  "Industria": "Industry",
  "Otra": "Other",
  "Mucho trabajo manual": "Too much manual work",
  "Pierdo clientes": "I lose customers",
  "Todo lo hago en Excel": "Everything is in Excel",
  "No tengo sistema": "I have no system",
  "Mi página no vende": "My website does not sell",
  "Necesito automatizar": "I need automation",
  "Necesito IA": "I need AI",
  "Quiero una App": "I want an app",
  "Otro": "Other",
  "1-5 empleados": "1–5 employees",
  "6-20 empleados": "6–20 employees",
  "20-50 empleados": "20–50 employees",
  "50+ empleados": "50+ employees",
  "Vender más": "Sell more",
  "Ahorrar tiempo": "Save time",
  "Organizar mi empresa": "Organize my company",
  "Automatizar procesos": "Automate processes",
  "Crear software": "Build software",
  "CRM personalizado": "Custom CRM",
  "Automatización con IA": "AI automation",
  "Dashboard ejecutivo": "Executive dashboard",
  "Tienda en línea / E-commerce": "Online store / Ecommerce",
  "Sitio web de alto rendimiento": "High-performance website",
  "App móvil a medida": "Custom mobile app",
  "Reducir tareas manuales repetitivas.": "Reduce repetitive manual tasks.",
  "Implementar seguimiento automático de leads y clientes.": "Introduce automatic follow-up for leads and customers.",
  "Centralizar información fuera de hojas de cálculo dispersas.": "Centralize information outside scattered spreadsheets.",
  "Adoptar un sistema central (CRM/ERP) para tu operación.": "Adopt a central system (CRM/ERP) for your operations.",
  "Optimizar tu sitio web para conversión.": "Optimize your website for conversion.",
  "Automatizar procesos clave con integraciones e IA.": "Automate key processes with integrations and AI.",
  "Incorporar IA en atención a clientes y operación.": "Use AI in customer service and operations.",
  "Desarrollar una app a medida para tu operación.": "Develop a custom app for your operations.",
  "Diagnosticar a fondo tu necesidad específica.": "Assess your specific needs in depth.",
  "Ya utilizas herramientas digitales.": "You already use digital tools.",
  "No dependes por completo de hojas de cálculo dispersas.": "You do not depend entirely on scattered spreadsheets.",
  "Tu equipo tiene el tamaño suficiente para justificar automatización a escala.": "Your team is large enough to justify automation at scale.",
  "Ya identificas con claridad hacia dónde quieres llevar tu operación.": "You have a clear direction for improving your operations.",
  "Diste el primer paso al evaluar la madurez digital de tu empresa.": "You took the first step by assessing your company’s digital maturity.",
  "Existe una oportunidad clara de automatización en tu operación.": "There is a clear opportunity to automate your operations.",
  "Centralizar información.": "Centralize information.",
  "Reducir tareas manuales.": "Reduce manual tasks.",
  "Automatizar seguimiento de clientes.": "Automate customer follow-up."
};
export const diagnosticLabel=(text:string,locale:Locale):string=>locale==="es"?text:(english[text]??text.replace("semanas","weeks"));
