'use client';
import {useEffect,useRef,type ReactNode,type MouseEvent} from 'react';
import {usePathname} from 'next/navigation';
import {enter} from './motion-utils';
import {initializeDiagnostic} from './diagnostic-client';
export function PublicInteractions({children}:{children:ReactNode}){
 const path=usePathname();const root=useRef<HTMLDivElement>(null);const opener=useRef<HTMLElement|null>(null);
 useEffect(()=>{document.documentElement.lang=path.startsWith('/en')?'en':'es';root.current?.querySelectorAll<HTMLAnchorElement>('.language-link').forEach(lang=>{lang.href=path.startsWith('/en')?(path.slice(3)||'/'):'/en'+(path==='/'?'':path);});root.current?.querySelectorAll<HTMLAnchorElement>('.site-header nav a').forEach(a=>{const href=new URL(a.href).pathname.replace(/\/$/,'');if(path===href||path.startsWith(href+'/'))a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});initializeDiagnostic();const dialogs=root.current?.querySelectorAll<HTMLDialogElement>('dialog');const close=()=>{if(root.current?.querySelector('dialog[open]'))return;root.current?.querySelectorAll('.menu-toggle').forEach(b=>b.setAttribute('aria-expanded','false'));document.documentElement.style.removeProperty('overflow');opener.current?.focus({preventScroll:true});};dialogs?.forEach(d=>d.addEventListener('close',close));return()=>dialogs?.forEach(d=>d.removeEventListener('close',close));},[path]);
 useEffect(()=>{let frame=0;const update=()=>{frame=0;if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;root.current?.querySelectorAll<HTMLElement>('.home-service-image,.service-detail-visual').forEach(el=>{const rect=el.getBoundingClientRect();if(rect.bottom<0||rect.top>innerHeight)return;const y=Math.max(-4,Math.min(4,(innerHeight/2-rect.top-rect.height/2)/innerHeight*8));el.classList.add('service-parallax');el.style.setProperty('--service-depth',`${y}%`);});};const scroll=()=>{if(!frame)frame=requestAnimationFrame(update);};window.addEventListener('scroll',scroll,{passive:true});update();return()=>{window.removeEventListener('scroll',scroll);cancelAnimationFrame(frame);};},[path]);
 useEffect(()=>{const widget=root.current?.querySelector<HTMLElement>('.wa-float');if(!widget)return;const messages=path.startsWith('/en')?['Hi, I would like more information.','Hi, I am interested in automating my business.','I have an idea for a website or app.','I would like to discuss my project.']:['Hola, quiero más información.','Hola, me interesa automatizar mi negocio.','Tengo una idea para una web o app.','Quiero platicar sobre mi proyecto.'];let index=0;const timer=setInterval(()=>{if(document.hidden||widget.matches(':hover')||widget.contains(document.activeElement)||widget.classList.contains('wa-quiet')||matchMedia('(prefers-reduced-motion: reduce)').matches)return;index=(index+1)%messages.length;const text=widget.querySelector<HTMLElement>('[data-wa-text]');if(text){text.textContent=messages[index];text.animate([{opacity:0,transform:'translateY(6px)'},{opacity:1,transform:'none'}],{duration:320});}widget.querySelectorAll<HTMLAnchorElement>('a').forEach(a=>{const url=new URL(a.href);url.searchParams.set('text',messages[index]);a.href=url.href;});},6500);return()=>clearInterval(timer);},[path]);
 useEffect(()=>{const host=root.current;if(!host)return;const buttons=Array.from(host.querySelectorAll<HTMLButtonElement>('[data-filter]'));const search=host.querySelector<HTMLInputElement>('[data-search-input]');let active=buttons[0]?.dataset.filter;const filter=()=>{let visible=0;const query=(search?.value??'').trim().toLocaleLowerCase();host.querySelectorAll<HTMLElement>('.work-card').forEach(card=>{card.hidden=(active!==buttons[0]?.dataset.filter&&card.dataset.category!==active)||!(card.dataset.search??'').includes(query);if(!card.hidden)visible++;});const empty=host.querySelector<HTMLElement>('.empty-state');if(empty)empty.hidden=visible>0;};const handlers=buttons.map(button=>{const handler=()=>{active=button.dataset.filter;buttons.forEach(b=>b.setAttribute('aria-pressed',String(b===button)));filter();};button.addEventListener('click',handler);return()=>button.removeEventListener('click',handler);});search?.addEventListener('input',filter);return()=>{handlers.forEach(clean=>clean());search?.removeEventListener('input',filter);};},[path]);
 useEffect(()=>{const host=root.current;if(!host)return;const reduced=matchMedia('(prefers-reduced-motion: reduce)');const art=Array.from(host.querySelectorAll<HTMLElement>('.service-art .art,.sector-art,.method-symbol'));const visible=new Set<Element>();const sync=()=>art.forEach(el=>el.classList.toggle('art-active',visible.has(el)&&!document.hidden&&!reduced.matches));const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(entry.isIntersecting)visible.add(entry.target);else visible.delete(entry.target);}sync();},{threshold:.1});art.forEach(el=>observer.observe(el));document.addEventListener('visibilitychange',sync);reduced.addEventListener('change',sync);const reveals=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){reveals.unobserve(entry.target);enter(entry.target as HTMLElement);}}));host.querySelectorAll<HTMLElement>('[data-motion],.service-row,.work-card,.method-list>article,.cta-section').forEach(el=>{if(el.getBoundingClientRect().top>=innerHeight)reveals.observe(el);});return()=>{observer.disconnect();reveals.disconnect();document.removeEventListener('visibilitychange',sync);reduced.removeEventListener('change',sync);};},[path]);
 const click=(event:MouseEvent<HTMLDivElement>)=>{if(event.ctrlKey||event.metaKey||event.shiftKey||event.altKey||!(event.target instanceof Element))return;const target=event.target.closest<HTMLElement>('a,button,dialog');if(!target)return;const dismiss=(dialog:HTMLDialogElement|null)=>{if(!dialog)return;if(matchMedia('(prefers-reduced-motion: reduce)').matches){dialog.close();return;}dialog.classList.add('is-closing');setTimeout(()=>{dialog.close();dialog.classList.remove('is-closing');},220);};
 const show=(id:string)=>{const dialog=document.getElementById(id);if(!(dialog instanceof HTMLDialogElement))return;event.preventDefault();opener.current=target.closest('dialog')?root.current?.querySelector<HTMLElement>('.menu-toggle')??target:target;root.current?.querySelectorAll<HTMLDialogElement>('dialog[open]').forEach(d=>{if(d!==dialog)d.close();});initializeDiagnostic();dialog.showModal();document.documentElement.style.overflow='hidden';if(id==='site-menu')target.setAttribute('aria-expanded','true');if(!matchMedia('(prefers-reduced-motion: reduce)').matches)dialog.animate([{opacity:0,transform:'translateY(10px)'},{opacity:1,transform:'none'}],{duration:260,easing:'ease-out'});};
 if(target.matches('.wa-float button')){event.preventDefault();target.closest('.wa-float')?.classList.add('wa-quiet');}
 else if(target.matches('[data-open-diagnostic]')||(target instanceof HTMLAnchorElement&&/^\/(en\/)?diagnostico\/?$/.test(new URL(target.href).pathname)))show('diagnostic-modal');else if(target.matches('.menu-toggle'))show('site-menu');else if(target.dataset.projectPopup)show(`project-popup-${target.dataset.projectPopup}`);else if(target.matches('[data-close-diagnostic],[data-close-menu],.diagnostic-close')){event.preventDefault();dismiss(target.closest('dialog'));}else if(target.matches('[data-start-diagnostic]')){event.preventDefault();const card=target.closest('.home-diagnostic-card');const intro=card?.querySelector<HTMLElement>('[data-diagnostic-intro]');const panel=card?.querySelector<HTMLElement>('[data-inline-diagnostic]');if(intro)intro.hidden=true;if(panel)panel.hidden=false;initializeDiagnostic();}else if(target instanceof HTMLDialogElement){const r=target.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dismiss(target);}else if(target.matches('a[href]'))target.closest('dialog')?.close();
 };
 return <div ref={root} className="public-website" data-pixel-home={path==='/'||path==='/en'?'':undefined} onClickCapture={click}>{children}</div>;
}
