'use client';
import {useState,type FormEvent} from 'react';
import {submitDiagnostic} from '@/app/actions';
import {diagnosticSchema} from './diagnostic-logic';
export function LeadFollowup(){
 const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [done,setDone]=useState(false);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;const form=event.currentTarget;if(!form.reportValidity())return;const fields=new FormData(form);let answers;try{answers=diagnosticSchema.parse(JSON.parse(form.closest<HTMLElement>('.wizard')?.dataset.answers??'null'));}catch{setMessage('Completa el diagnóstico antes de solicitar seguimiento.');return;}setBusy(true);setMessage('');try{const result=await submitDiagnostic({...answers,name:String(fields.get('name')??''),email:String(fields.get('email')??''),phone:String(fields.get('phone')??''),empresa:String(fields.get('empresa')??''),website:String(fields.get('website')??''),consent:String(fields.get('consent')??'')});if(result.ok){setDone(true);setMessage('Recibimos tu diagnóstico. Nuestro equipo podrá dar seguimiento a tu solicitud.');}else setMessage(result.message);}catch{setMessage('No pudimos enviar tu solicitud. Puedes intentar de nuevo o compartirla por WhatsApp.');}finally{setBusy(false);}}
 return <details className="public-lead"><summary>Prefiero que me contacten</summary>{!done&&<form onSubmit={submit}><p>Comparte tus datos para que nuestro equipo revise tu diagnóstico.</p><label>Nombre<input name="name" autoComplete="name" required minLength={2}/></label><label>Correo electrónico<input type="email" name="email" autoComplete="email" required/></label><label>Teléfono (opcional)<input name="phone" type="tel" autoComplete="tel"/></label><label>Empresa (opcional)<input name="empresa" autoComplete="organization"/></label><div hidden><label>No completar<input name="website" tabIndex={-1} autoComplete="off"/></label></div><label><input type="checkbox" name="consent" required/> Acepto el <a href="/aviso-de-privacidad" target="_blank" rel="noopener noreferrer">Aviso de Privacidad</a> y solicito que me contacten.</label><button type="submit" disabled={busy}>{busy?'Enviando…':'Solicitar seguimiento'}</button></form>}<p role="status">{message}</p></details>;
}
