import { escapeHTML as esc } from './catalog.js';
import type { Locale } from './i18n.js';
function rawArt(kind='web',label='PixelTEC'):string {
  if(kind==='orbit') return `<div class="art art-orbit" aria-hidden="true"><i class="orbit o1"></i><i class="orbit o2"></i><i class="orbit o3"></i><div class="core">✳</div><b class="sat s1">IA</b><b class="sat s2">↗</b><b class="sat s3">⌘</b><span class="art-caption">SISTEMAS CONECTADOS / 01</span></div>`;
  if(kind==='grid') return `<div class="art art-grid" aria-hidden="true"><div class="tile-grid">${Array.from({length:9},(_,i)=>`<i>${['↗','⌘','✳','01','↗','◎','✦','02','↗'][i]}</i>`).join('')}</div><span class="art-caption">ESTRATEGIA + TECNOLOGÍA</span></div>`;
  if(kind==='chat') return `<div class="art art-chat" aria-hidden="true"><div class="phone"><div class="phone-top"><span class="avatar">P</span><span>PixelTEC IA<small>En línea</small></span><b>···</b></div><div class="bubble">Hola. ¿Qué construimos hoy?</div><div class="bubble mine">Una mejor forma de trabajar ↗</div><div class="bubble">Conectemos las piezas.<div class="chat-lines"><i></i><i></i></div></div><div class="typing">● ● ●</div><div class="phone-input">Escribe un mensaje <b>↑</b></div></div><span class="art-caption">CONVERSACIONES CON PROPÓSITO</span></div>`;
  const hotel=kind==='hotel',store=kind==='store',clinic=kind==='clinic';
  return `<div class="art art-${kind}" aria-hidden="true"><div class="mock-browser"><div class="browser-bar"><span>● ● ●</span><small>${esc(label)}</small><span>↗</span></div>${hotel?`<div class="hotel-scene"><span>VILLA / NOGAL</span><div class="sun"></div><div class="arch"></div><strong>Un lugar<br>para volver.</strong><i>EXPLORAR →</i></div>`:store?`<div class="store-scene"><small>OBJETOS / MATERIA / FORMA</small><strong>Hecho para<br>permanecer.</strong><div class="vases"><i></i><i></i><i></i></div></div>`:`<div class="dashboard"><aside><b>${clinic?'✚':'✳'}</b><i></i><i></i><i></i><i></i></aside><div><small>${clinic?'MI AGENDA':'VISTA GENERAL'}</small><h4>${clinic?'Un día conectado.':'Todo en su lugar.'}</h4><div class="mini-stats"><i></i><i></i><i></i></div><div class="chart">${[42,67,50,86,62,94,76,100].map(h=>`<i style="height:${h}%"></i>`).join('')}</div><div class="mock-lines"><i></i><i></i></div></div></div>`}</div><span class="art-caption">${hotel?'EXPERIENCIA DIGITAL':store?'DISEÑO QUE CONECTA':'OPERACIÓN SIN FRICCIÓN'}</span></div>`;
}

const translations:Record<string,string>={"SISTEMAS CONECTADOS": "CONNECTED SYSTEMS", "ESTRATEGIA + TECNOLOGÍA": "STRATEGY + TECHNOLOGY", "En línea": "Online", "Hola. ¿Qué construimos hoy?": "Hello. What are we building today?", "Una mejor forma de trabajar": "A better way to work", "Conectemos las piezas.": "Let’s connect the pieces.", "Escribe un mensaje": "Type a message", "CONVERSACIONES CON PROPÓSITO": "PURPOSEFUL CONVERSATIONS", "Un lugar<br>para volver.": "A place<br>to return to.", "EXPLORAR": "EXPLORE", "OBJETOS / MATERIA / FORMA": "OBJECTS / MATERIAL / FORM", "Hecho para<br>permanecer.": "Made<br>to last.", "MI AGENDA": "MY SCHEDULE", "VISTA GENERAL": "OVERVIEW", "Un día conectado.": "A connected day.", "Todo en su lugar.": "Everything in place.", "EXPERIENCIA DIGITAL": "DIGITAL EXPERIENCE", "DISEÑO QUE CONECTA": "DESIGN THAT CONNECTS", "OPERACIÓN SIN FRICCIÓN": "FRICTIONLESS OPERATIONS", "PixelTEC IA": "PixelTEC AI", ">IA<": ">AI<"};
export function art(kind='web',label='PixelTEC',locale:Locale='es'):string{let html=rawArt(kind,label);if(locale==='en')for(const [es,en] of Object.entries(translations))html=html.replaceAll(es,en);return html;}
