import {bi,type Bilingual} from './i18n.js';
export interface Feature {title:Bilingual;body:Bilingual;}
export interface ContentItem {id:string;path:string;title:Bilingual;description:Bilingual;category:Bilingual;visual:string;features:Feature[];source:string;}
const feature=(es:string,en:string,body:string,translation:string):Feature=>({title:bi(es,en),body:bi(body,translation)});
export const company={
 tagline:bi('Desde Puerto Vallarta para todo México','From Puerto Vallarta, for businesses across Mexico'),
 description:bi('Construimos páginas web, apps y software a la medida, y automatizamos tu operación con IA y WhatsApp. Desde Puerto Vallarta, para pymes y empresas de Bahía de Banderas, Guadalajara y todo México.','We build websites, apps and custom software, and automate your operations with AI and WhatsApp. Based in Puerto Vallarta, we work with businesses in Bahía de Banderas, Guadalajara and across Mexico.'),
 about:bi('PixelTEC, liderada por Miguel Robles, nació para cerrar la brecha entre la estrategia de negocio y la ejecución tecnológica. Entendemos que el código es una herramienta poderosa, pero su verdadero valor se desbloquea cuando se alinea con objetivos comerciales claros.','Led by Miguel Robles, PixelTEC was founded to bridge business strategy and technology execution. Code is a powerful tool; its real value emerges when it supports clear business goals.'),
 team:bi('Cada proyecto lo dirige un arquitecto líder y se apoya en una red de especialistas —diseño, QA, infraestructura, branding— que se integra según lo que ese proyecto exige.','Every project is led by a software architect and supported by a network of specialists in design, quality assurance, infrastructure and branding, assembled around the needs of that project.'),
 phone:'+52 (322) 137-8336',email:'contacto@pixeltec.mx', whatsapp:'https://api.whatsapp.com/send?phone=523221378336'
};
export const serviceContent:ContentItem[]=[
 {id:'automation',path:'/services/automatizacion/',title:bi('Automatización con IA','AI automation'),category:bi('Flujos · Integraciones · IA','Workflows · Integrations · AI'),visual:'orbit',source:'https://pixeltec.mx/services/automatizacion',description:bi('Eliminamos tareas repetitivas con bots, scripts e IA aplicada a tu operación diaria. Conectamos sistemas y automatizamos la atención en WhatsApp con WhatsAgent como parte de tu operación.','We remove repetitive tasks with bots, scripts and AI built into your daily operations. We connect systems and automate WhatsApp customer service with WhatsAgent as part of your operations.'),features:[
 feature('Bots que atienden','Customer service bots','Preguntas frecuentes y calificación de prospectos en WhatsApp, Telegram o tu sitio web.','Frequently asked questions and lead qualification on WhatsApp, Telegram or your website.'),
 feature('Datos sin recapturas','Data without duplicate entry','Lectura y procesamiento de documentos, validación de datos y conexión entre tus herramientas.','Document processing, data validation and connections between your existing tools.'),
 feature('Reportes automáticos','Automated reporting','Consolidamos información de Excel, bases de datos y APIs en reportes listos para analizar.','We bring together spreadsheets, databases and APIs in reports ready for analysis.') ]},
 {id:'web',path:'/services/ecosistemas-web/',title:bi('Desarrollo Web & Apps','Web & app development'),category:bi('Web · Plataformas · Experiencias','Web · Platforms · Experiences'),visual:'web',source:'https://pixeltec.mx/services/ecosistemas-web',description:bi('Aplicaciones web robustas, CRMs personalizados y sitios corporativos rápidos. Diseñamos arquitecturas escalables con Next.js, React y tecnologías adecuadas a tu operación.','Robust web applications, custom CRMs and fast business websites. We build scalable architectures with Next.js, React and technologies suited to your operations.'),features:[
 feature('Tu operación, conectada','Connected operations','CRMs y dashboards a la medida para centralizar información y facilitar decisiones.','Custom CRMs and dashboards that bring information together and support decisions.'),
 feature('Experiencias que funcionan','Experiences that work','Sitios corporativos, tiendas en línea y aplicaciones web progresivas, según el alcance de tu proyecto.','Business websites, online stores and progressive web apps, based on your project scope.'),
 feature('Sistemas que se hablan','Systems that talk','Integraciones con servicios de facturación, logística y marketing para un flujo de datos unificado.','Integrations with invoicing, logistics and marketing services for a connected flow of data.') ]},
 {id:'whatsagent',path:'/pixelbot/',title:bi('WhatsAgent · IA en WhatsApp','WhatsAgent · WhatsApp AI'),category:bi('Conversación · Atención · Ventas','Conversations · Service · Sales'),visual:'chat',source:'https://pixeltec.mx/pixelbot',description:bi('Un agente con la identidad de tu marca. Responde con información aprobada, califica prospectos y entrega la conversación a tu equipo con contexto cuando hace falta.','An AI agent with your brand identity. It answers using approved information, qualifies leads and hands conversations to your team with context when needed.'),features:[
 feature('Con tu nombre y tus reglas','Your name. Your rules.','Configura identidad, tono, conocimiento, temas permitidos y límites. Prueba al agente antes de publicarlo.','Set its identity, tone, knowledge, allowed topics and boundaries. Test your agent before publishing it.'),
 feature('El control sigue en tu equipo','Your team stays in control','Modos Bot, Humano y Pausa. Cuando una persona atiende, el bot guarda silencio.','Bot, Human and Pause modes. When a person takes over, the bot stays silent.'),
 feature('Integraciones según alcance','Integrations matched to scope','Puede conectarse a CRM, ERP, agenda o inventario cuando esa integración forma parte del alcance aprobado.','It can connect to a CRM, ERP, calendar or inventory when that integration is included in the agreed scope.') ]},
 {id:'consulting',path:'/services/consultoria/',title:bi('Consultoría & Soporte TI','IT consulting & support'),category:bi('Estrategia · Procesos · Soporte','Strategy · Processes · Support'),visual:'grid',source:'https://pixeltec.mx/services/consultoria',description:bi('Diagnóstico estratégico, transformación digital y rediseño UI/UX para modernizar procesos. Acompañamos a tu equipo de adentro hacia afuera.','Strategic assessment, digital transformation and UI/UX redesign to modernize your processes. We work alongside your team from the inside out.'),features:[
 feature('Entender antes de construir','Understand before building','Auditamos sistemas y procesos para detectar cuellos de botella y oportunidades de mejora.','We audit systems and processes to identify bottlenecks and opportunities to improve.'),
 feature('Una ruta con prioridades','A roadmap with priorities','Definimos una hoja de ruta tecnológica, herramientas e indicadores alineados con tu negocio.','We define a technology roadmap, tools and metrics aligned with your business.'),
 feature('Acompañar la adopción','Support for adoption','Capacitación, modernización de interfaces y soporte para que el equipo aproveche las herramientas.','Training, interface modernization and support to help your team get value from its tools.') ]}
];
export const method:Feature[]=[
 feature('Entender','Understand','Diagnosticamos cómo opera tu negocio y qué necesita resolver primero.','We assess how your business works and what it needs to solve first.'),
 feature('Diseñar','Design','Definimos alcance, arquitectura y experiencia alrededor de tus procesos.','We define scope, architecture and the experience around your processes.'),
 feature('Construir y validar','Build and validate','Desarrollamos por etapas, probamos e integramos con los sistemas acordados.','We build in stages, test and integrate with the agreed systems.'),
 feature('Acompañar y evolucionar','Support and evolve','Ayudamos a tu equipo a adoptar la solución y priorizar las siguientes mejoras.','We help your team adopt the solution and prioritize the next improvements.')
];
export interface CaseStudy {id:string;path:string;name:string;category:Bilingual;visual:string;description:Bilingual;scope:Bilingual;quote:Bilingual;person:string;role:Bilingual;source:string;}
export const caseStudies:CaseStudy[]=[
 {id:'villa-nogal',path:'/proyectos/villa-nogal/',name:'Villa Nogal',category:bi('Web','Web'),visual:'hotel',description:bi('Hotel boutique en San Sebastián del Oeste, Jalisco. Un sitio bilingüe, motor de reservas propio y CRM hotelero a la medida.','A boutique hotel in San Sebastián del Oeste, Jalisco. A bilingual website, direct booking engine and custom hotel CRM.'),scope:bi('Disponibilidad por habitación, gestión de huéspedes y contenidos del destino administrados desde el panel del hotel.','Room availability, guest management and destination content managed through the hotel dashboard.'),quote:bi('PixelTEC transformó por completo nuestra presencia digital. El nuevo sistema de reservas a medida no solo es elegante, sino que optimizó nuestras operaciones diarias de manera increíble.','PixelTEC completely transformed our digital presence. The new custom booking system is not only elegant; it has also made an incredible difference to our daily operations.'),person:'Aidee García',role:bi('Directora, Villa Nogal','Director, Villa Nogal'),source:'https://pixeltec.mx/industrias/hoteles'},
 {id:'pipas-tondoroque',path:'/proyectos/pipas-tondoroque/',name:'Pipas Tondoroque',category:bi('Automatización','Automation'),visual:'dashboard',description:bi('Automatización de pedidos y gestión logística para acompañar la operación de una distribuidora de agua.','Order automation and logistics management to support a water distribution business.'),scope:bi('Tecnología y consultoría para ordenar los pedidos y facilitar la atención a clientes.','Technology and consulting to organize orders and support customer service.'),quote:bi('La automatización de nuestros pedidos y la reestructuración de la gestión logística nos ha ahorrado incontables horas. Ahora atendemos a nuestros clientes de forma mucho más rápida y sin errores.','Automating our orders and restructuring logistics management has saved us countless hours. We now serve our customers much faster and without errors.'),person:'Juan Antonio Sánchez',role:bi('Director General, Pipas Tondoroque','Managing Director, Pipas Tondoroque'),source:'https://pixeltec.mx/'},
 {id:'barro-stock',path:'/proyectos/barro-stock/',name:'Barro Stock',category:bi('Web','Web'),visual:'store',description:bi('Arquitectura web y control de inventario diseñados alrededor de las necesidades del negocio.','Web architecture and inventory control designed around the needs of the business.'),scope:bi('Una plataforma para conectar la presencia digital con el control del inventario.','A platform that connects the digital experience with inventory control.'),quote:bi('La arquitectura web y el control de inventario que desarrollaron para nosotros nos ha dado una ventaja competitiva enorme. La plataforma es robusta, rápida y exactamente lo que necesitábamos.','The web architecture and inventory control they developed for us have given us a tremendous competitive advantage. The platform is robust, fast and exactly what we needed.'),person:'Francisco Arredondo',role:bi('CEO, Barro Stock','CEO, Barro Stock'),source:'https://pixeltec.mx/'},
 {id:'smile-more',path:'/proyectos/smile-more/',name:'Smile More',category:bi('Plataformas','Platforms'),visual:'clinic',description:bi('Plataforma de gestión y sitio público para una clínica dental con sedes en Guadalajara y Guamúchil.','A management platform and public website for a dental clinic with locations in Guadalajara and Guamúchil.'),scope:bi('Agenda, expedientes por rol, cobro en caja, comprobantes PDF y recordatorios por correo. WhatsApp está disponible como siguiente paso.','Scheduling, role-based patient records, front-desk payments, PDF receipts and email reminders. WhatsApp is available as a next step.'),quote:bi('El sistema de gestión integral para la clínica y el rediseño del sitio web superaron todas nuestras expectativas. Hemos mejorado nuestra captación de pacientes notablemente.','The integrated clinic management system and website redesign exceeded all our expectations. We have significantly improved our patient acquisition.'),person:'Polett Niebla',role:bi('Fundadora, Smile More','Founder, Smile More'),source:'https://pixeltec.mx/industrias/clinicas-dentales'},
 {id:'materiales-de-barro',path:'/proyectos/materiales-de-barro/',name:'Materiales de Barro',category:bi('Web','Web'),visual:'store',description:bi('Un ecosistema digital a la medida para modernizar la operación de un negocio tradicional.','A custom digital ecosystem to modernize the operations of a traditional business.'),scope:bi('Digitalización orientada al control del negocio y al crecimiento comercial.','Digital transformation focused on business control and commercial growth.'),quote:bi('Digitalizar un negocio tradicional parecía un reto imposible, pero el equipo diseñó un ecosistema a la medida que nos permitió modernizarnos, escalar ventas y tener control total.','Digitalizing a traditional business seemed impossible, but the team designed a custom ecosystem that allowed us to modernize, grow sales and gain full control.'),person:'Juan Sánchez',role:bi('Fundador, Materiales de Barro','Founder, Materiales de Barro'),source:'https://pixeltec.mx/'}
];
// These portfolio entries use material supplied by Miguel on 2026-10-05.
// Empty testimonial fields mean no testimonial was supplied; never borrow another client's quote.
caseStudies.push(
 {id:'dalk',path:'/proyectos/dalk/',name:'DALK',category:bi('Web','Web'),visual:'store',description:bi('Presencia digital para una marca mexicana de fajas y moda, con el producto al centro de la experiencia.','A digital presence for a Mexican shapewear and fashion brand, with the product at the heart of the experience.'),scope:bi('Diseño web de producto, presentación de la marca y conexión con sus canales de contacto y venta.','Product-focused web design, brand presentation and connections to contact and sales channels.'),quote:bi('',''),person:'',role:bi('',''),source:'https://dalk.mx/'},
 {id:'velank',path:'/proyectos/velank/',name:'Velank',category:bi('Web','Web'),visual:'store',description:bi('Una experiencia digital de moda y beachwear inspirada en el estilo de vida de Puerto Vallarta.','A fashion and beachwear digital experience inspired by the Puerto Vallarta lifestyle.'),scope:bi('Diseño de una experiencia de catálogo que conecta las colecciones, el producto y la identidad visual de la marca.','A catalog experience connecting collections, products and the visual identity of the brand.'),quote:bi('',''),person:'',role:bi('',''),source:''},
 {id:'transportes-sanchez-jr',path:'/proyectos/transportes-sanchez-jr/',name:'Transportes Sánchez JR',category:bi('Web','Web'),visual:'dashboard',description:bi('Presencia web para una empresa de materiales, maquinaria y transporte para la construcción.','A web presence for a construction materials, machinery and transport business.'),scope:bi('Presentación de servicios, flota y canales de cotización para clientes de Puerto Vallarta y Bahía de Banderas.','Services, fleet and quotation channels for customers in Puerto Vallarta and Bahía de Banderas.'),quote:bi('',''),person:'',role:bi('',''),source:''},
 {id:'subsify',path:'/proyectos/subsify/',name:'Subsify',category:bi('Apps','Apps'),visual:'grid',description:bi('App móvil para organizar suscripciones, visualizar gastos y consultar los próximos cobros en un solo lugar.','A mobile app to organize subscriptions, review spending and see upcoming charges in one place.'),scope:bi('Una experiencia móvil con suscripciones, gastos, calendario, familia y búsqueda. Diseño de pantallas y experiencia de producto en español e inglés.','A mobile experience with subscriptions, spending, calendar, family and search. Screen design and product experience in Spanish and English.'),quote:bi('',''),person:'',role:bi('',''),source:''}
);
export const featuredCaseStudies=['villa-nogal','subsify','dalk','smile-more','materiales-de-barro'].map(id=>{const c=caseStudies.find(c=>c.id===id);if(!c)throw new Error('Missing featured project: '+id);return c;});
export const testimonials=caseStudies.filter(c=>c.person && c.quote.es && c.quote.en);
export const industryContent:ContentItem[]=[
 {id:'salud',path:'/industrias/clinicas-dentales/',title:bi('Salud dental','Dental care'),category:bi('Agenda · Expediente · Operación','Scheduling · Records · Operations'),visual:'clinic',source:'https://pixeltec.mx/industrias/clinicas-dentales',description:bi('Citas, expedientes y cobro en un sistema propio de la clínica, con permisos claros para administración, doctores y recepción.','Appointments, patient records and payments in a clinic-owned system, with clear permissions for administrators, doctors and reception.'),features:[feature('Agenda conectada','Connected scheduling','Citas por doctor y sede, alta de pacientes y reprogramación.','Appointments by doctor and location, patient registration and rescheduling.'),feature('Expedientes por rol','Role-based patient records','Historial y archivos clínicos accesibles solo al personal autorizado.','Patient history and clinical files accessible only to authorized staff.'),feature('Cobro y recordatorios','Payments and reminders','Comprobantes PDF, cobro en caja y confirmaciones y recordatorios por correo.','PDF receipts, front-desk payments, email confirmations and reminders.')]},
 {id:'hoteleria',path:'/industrias/hoteles/',title:bi('Hotelería','Hospitality'),category:bi('Reservas · Huéspedes · Experiencia','Bookings · Guests · Experience'),visual:'hotel',source:'https://pixeltec.mx/industrias/hoteles',description:bi('Motor de reservas propio y CRM hotelero a la medida, con sitio bilingüe y gestión de huéspedes bajo la marca del hotel.','A direct booking engine and custom hotel CRM, with a bilingual website and guest management under the hotel’s own brand.'),features:[feature('Reservas directas','Direct bookings','Disponibilidad por habitación y un flujo de reserva completo dentro del sitio.','Room availability and a complete booking journey on the hotel website.'),feature('Español e inglés','Spanish and English','Páginas con URLs propias para huéspedes nacionales y extranjeros.','Pages with separate URLs for domestic and international guests.'),feature('Control desde el panel','Dashboard control','Habitaciones, tarifas, fotos y disponibilidad administradas por el hotel.','Rooms, rates, photos and availability managed by the hotel.')]},
 {id:'logistica',path:'/industrias/#logistica',title:bi('Logística y transporte','Logistics & transport'),category:bi('Operación · Coordinación · Soporte','Operations · Coordination · Support'),visual:'dashboard',source:'https://pixeltec.mx/industrias',description:bi('Digitalizamos la operación de empresas de transporte con un sistema propio, consultoría operativa y soporte después de la entrega.','We digitalize transport operations with a custom system, operational consulting and support after delivery.'),features:[]},
 {id:'agua',path:'/industrias/#agua',title:bi('Distribución de agua','Water distribution'),category:bi('Pedidos · Presencia digital · Consultoría','Orders · Digital presence · Consulting'),visual:'orbit',source:'https://pixeltec.mx/industrias',description:bi('Presencia digital, sistemas de pedidos a la medida y consultoría tecnológica y operativa para distribuidoras de agua en pipas.','Digital presence, custom order management and technology and operational consulting for water tanker distributors.'),features:[]},
 {id:'comercio',path:'/industrias/#comercio',title:bi('Moda y comercio especializado','Fashion & specialty retail'),category:bi('Catálogo · Identidad · Comercio','Catalog · Identity · Commerce'),visual:'store',source:'https://pixeltec.mx/industrias',description:bi('Tiendas en línea y catálogos con identidad propia. Venta por Instagram, WhatsApp o carrito propio, según la etapa de la marca.','Online stores and catalogs with a distinct brand identity. Sales through Instagram, WhatsApp or a shopping cart, depending on the brand’s stage.'),features:[]},
 {id:'solar',path:'/industrias/#solar',title:bi('Energía solar','Solar energy'),category:bi('Cotización · Dimensionamiento · Control','Quotes · System sizing · Control'),visual:'grid',source:'https://pixeltec.mx/industrias',description:bi('Cotizador fotovoltaico a la medida: dimensionamiento de paneles e inversores, precios por cotización y roles de administrador y asesor.','Custom solar quoting software: panel and inverter sizing, pricing fixed per quote, and administrator and advisor roles.'),features:[]}
];
export interface Post {path:string;title:Bilingual;description:Bilingual;category:Bilingual;date:string;author:string;minutes:number;visual:string;sections:Feature[];}
export const editorial:Post[]=[
 {path:'/blog/sistema-administrativo-para-eficientar-tu-pyme-en-mexico/',title:bi('Sistema administrativo para eficientar tu PyME en México','Business management software for SMEs in Mexico'),description:bi('Cómo conectar ventas, inventario, clientes, cobranza y facturación en una sola operación.','How to connect sales, inventory, customers, receivables and invoicing in one operation.'),category:bi('Operación','Operations'),date:'2026-09-03',author:'Administrador',minutes:8,visual:'dashboard',sections:[feature('Una captura, procesos conectados','One entry, connected processes','El artículo explica cómo un sistema administrativo conecta ventas, inventario, clientes, cobranza y facturación para evitar capturas duplicadas.','The article explains how management software connects sales, inventory, customers, receivables and invoicing to prevent duplicate data entry.'),feature('Primero el diagnóstico','Start with an assessment','Antes de elegir un ERP o desarrollar a la medida, conviene identificar qué procesos pierden tiempo, dónde ocurren errores y qué necesita ver el dueño para decidir.','Before choosing an ERP or building custom software, identify where time is lost, where errors occur and what information the owner needs to make decisions.'),feature('Empieza por etapas','Start in stages','Prioriza los procesos que más afectan tu operación. Consolida el primer cambio con el equipo y después integra el siguiente.','Prioritize the processes that affect operations the most. Establish the first improvement with your team, then connect the next one.')]},
 {path:'/blog/como-automatizar-procesos-manuales-en-mi-negocio-guia-real/',title:bi('Cómo automatizar procesos manuales en mi negocio: guía real','How to automate manual business processes: a practical guide'),description:bi('Identifica las tareas repetitivas y empieza a modernizar tu operación sin cambiarlo todo de golpe.','Identify repetitive tasks and start modernizing your operations without changing everything at once.'),category:bi('Automatización','Automation'),date:'2026-09-03',author:'Miguel Robles',minutes:9,visual:'orbit',sections:[feature('Haz visible el trabajo repetitivo','Make repetitive work visible','Lista las tareas diarias, cuánto tarda cada una y cuántas veces se repite. Esa medición te ayuda a elegir el primer proceso.','List daily tasks, how long each one takes and how often it repeats. Use that measurement to choose the first process.'),feature('Digitalizar y automatizar','Digitalizing and automating','Pasar del papel a Excel cambia el soporte. Conectar un pedido con operación, facturación y seguimiento cambia el flujo de trabajo.','Moving from paper to a spreadsheet changes the medium. Connecting an order to operations, invoicing and follow-up changes the workflow.'),feature('Mide antes y después','Measure before and after','Empieza por pedidos, atención o seguimiento de clientes. Prueba un proceso, acompaña al equipo y decide el siguiente paso con datos.','Start with orders, customer service or follow-up. Test one process, support the team and use data to decide the next step.')]},
 {path:'/blog/que-datos-nunca-deberias-compartir-con-chatgpt-gemini-o-claude-en-tu-empresa/',title:bi('Qué datos nunca deberías compartir con ChatGPT, Gemini o Claude en tu empresa','What business data should you avoid sharing with public AI tools?'),description:bi('Criterios prácticos para cuidar información personal, secretos técnicos y datos confidenciales al usar IA.','Practical principles for protecting personal information, technical secrets and confidential data when using AI.'),category:bi('IA','AI'),date:'2026-09-02',author:'Miguel Robles',minutes:5,visual:'grid',sections:[feature('Identifica información sensible','Identify sensitive information','El artículo reúne categorías que requieren cuidado: datos personales, información financiera, contraseñas, llaves técnicas y comunicaciones privadas.','The article identifies categories that require care: personal data, financial information, passwords, technical keys and private communications.'),feature('Reduce lo que compartes','Minimize what you share','Sustituye datos identificables por marcadores y revisa las herramientas y configuraciones autorizadas por tu empresa.','Replace identifying information with placeholders and check the tools and settings approved by your company.'),feature('Un criterio compartido','A shared approach','Una política interna clara y capacitación ayudan a que el equipo sepa qué puede compartir, qué debe proteger y a quién consultar.','A clear internal policy and training help the team understand what it may share, what it must protect and whom to ask.')]},
 {path:'/blog/agente-de-ia-en-whatsapp-para-mi-negocio/',title:bi('Agente de IA en WhatsApp para mi negocio','A WhatsApp AI agent for your business'),description:bi('Qué automatizar, cuándo transferir a una persona y cómo preparar el conocimiento de tu negocio.','What to automate, when to hand over to a person and how to prepare your business knowledge.'),category:bi('IA','AI'),date:'2026-08-03',author:'Miguel Robles Sánchez',minutes:10,visual:'chat',sections:[feature('Empieza por lo frecuente','Start with frequent questions','Horarios, servicios y preguntas repetidas son un punto de partida. Prepara respuestas aprobadas antes de automatizar.','Opening hours, services and repeated questions are a starting point. Prepare approved answers before automating.'),feature('La salida humana importa','Human handover matters','Quejas, negociaciones y situaciones sensibles requieren criterio humano. El equipo debe recibir contexto para continuar la conversación.','Complaints, negotiations and sensitive situations call for human judgment. The team needs context to continue the conversation.'),feature('Conectar según el alcance','Connect according to scope','Agenda, inventario y estado de pedidos requieren integraciones definidas. WhatsAgent detalla capacidades y condiciones en su página de producto.','Scheduling, inventory and order status require defined integrations. WhatsAgent describes capabilities and conditions on its product page.')]},
 {path:'/blog/ia-para-pymes-en-mexico-guia-honesta-para-empezar-sin-quemar-dinero/',title:bi('IA para PyMEs en México: guía honesta para empezar sin quemar dinero','AI for SMEs in Mexico: an honest guide to getting started'),description:bi('Ordena el proceso, prueba una tarea útil y mide antes de invertir en una automatización más compleja.','Organize the process, test a useful task and measure before investing in more complex automation.'),category:bi('Estrategia','Strategy'),date:'2026-05-14',author:'Miguel Robles',minutes:8,visual:'web',sections:[feature('Entender antes de automatizar','Understand before automating','Documenta qué hace tu negocio y cómo responde hoy a sus clientes. Separa preguntas frecuentes de decisiones que requieren juicio humano.','Document what your business does and how it answers customers today. Separate frequent questions from decisions requiring human judgment.'),feature('IA como asistente','AI as an assistant','Redacción, resúmenes y organización de información son formas de explorar el valor de la IA con revisión del equipo.','Writing, summaries and organizing information are ways to explore the value of AI with your team reviewing the output.'),feature('Resultados, no entusiasmo','Measure results, not excitement','Evalúa horas recuperadas, tiempos de respuesta y calidad. Decide si conviene una herramienta existente o una solución propia con esa evidencia.','Assess time recovered, response times and quality. Use that evidence to decide between an existing tool and a custom solution.') ]}
];
export const faqContent:Feature[]=[
 feature('¿Por dónde empezamos?','Where do we start?','Con un diagnóstico de tu operación. Revisamos el reto y definimos qué conviene construir o mejorar primero.','With an assessment of your operations. We review the challenge and identify what to build or improve first.'),
 feature('¿Todo tiene que ser a la medida?','Does everything need to be custom built?','No. Primero entendemos el proceso. La solución puede ser una herramienta existente bien configurada, una integración o desarrollo a la medida.','No. We understand the process first. The answer may be a well-configured existing tool, an integration or custom development.'),
 feature('¿Trabajan fuera de Puerto Vallarta?','Do you work outside Puerto Vallarta?','Sí. Trabajamos con empresas de todo México, con presencia local en Puerto Vallarta, Bahía de Banderas, Guadalajara y Zapopan.','Yes. We work with businesses across Mexico, with a local presence in Puerto Vallarta, Bahía de Banderas, Guadalajara and Zapopan.'),
 feature('¿Qué pasa después de la entrega?','What happens after delivery?','Acompañamos la adopción y evolución de la solución. El soporte, las integraciones y las mejoras se definen en el alcance de cada proyecto.','We support adoption and evolution. Support, integrations and improvements are defined in each project’s scope.')
];

// WhatsAgent is part of automation; its existing detail URL remains available.
export const marketedServices=serviceContent.filter(s=>s.id!=='whatsagent');
