import {bi,type Bilingual,type Locale} from './i18n.js';
import {escapeHTML as esc} from './catalog.js';
import {company} from './content.js';
export function diagnosticWidget(locale:Locale):string {const x=(es:string,en:string):string=>locale==='es'?es:en;const tr=(s:Bilingual):string=>s[locale];const questions:[Bilingual,Bilingual[]][]=[
 [bi('¿En qué industria trabajas?','What industry are you in?'),[bi('Salud','Healthcare'),bi('Hotelería','Hospitality'),bi('Comercio','Retail'),bi('Logística','Logistics'),bi('Servicios','Services'),bi('Otra industria','Another industry')]],
 [bi('¿Qué te gustaría mejorar?','What would you like to improve?'),[bi('La atención al cliente','Customer service'),bi('La operación diaria','Daily operations'),bi('Mi presencia digital','My digital presence'),bi('La información del negocio','Business information')]],
 [bi('¿Cuál es tu punto de partida?','What is your starting point?'),[bi('Empezamos desde cero','We are starting from scratch'),bi('Tenemos herramientas aisladas','We have disconnected tools'),bi('Queremos evolucionar un sistema','We want to improve an existing system')]],
 [bi('¿Cuándo te gustaría empezar?','When would you like to start?'),[bi('Estoy explorando','I am exploring'),bi('En los próximos meses','In the next few months'),bi('Tenemos un reto inmediato','We have an immediate challenge')]]
 ];return `<div class="wizard"><div class="wizard-top"><span class="eyebrow" data-step-label>${x('PASO','STEP')} 01 / 04</span><div class="progress-track"><i data-progress style="width:25%"></i></div></div><form id="diagnostic-form">${questions.map(([q,options],i)=>`<fieldset data-step="${i}" ${i?'hidden="true"':''}><legend>${tr(q)}</legend><p>${x('Selecciona la opción que mejor te describe.','Choose the option that best describes you.')}</p><div class="wizard-options">${options.map((t,j)=>`<label><input type="radio" name="step${i}" value="${esc(tr(t))}" ${j===0?'required':''}><span>${tr(t)}<b>↗</b></span></label>`).join('')}</div></fieldset>`).join('')}<p data-wizard-error role="alert"></p><div class="wizard-actions"><button type="button" class="text-button" data-prev hidden="true">← ${x('Atrás','Back')}</button><button type="button" class="button" data-next>${x('Continuar','Continue')} →</button></div></form><div data-summary hidden="true"><p class="eyebrow">${x('TU PUNTO DE PARTIDA','YOUR STARTING POINT')}</p><h2>${x('Una base para<br>conversar.','A starting point<br>for a conversation.')}</h2><dl data-summary-list></dl><p class="form-message">${x('Todavía no se ha enviado nada. Revisa el resumen y decide si quieres compartirlo.','Nothing has been sent. Review the summary and choose whether to share it.')}</p><a class="button" data-share-summary href="${company.whatsapp}">${x('Compartir por WhatsApp','Share on WhatsApp')} ↗</a><button type="button" class="text-button" data-restart>${x('Volver a empezar','Start again')} ↗</button></div></div>`;}
