import { industryArt } from './industry-art.js';
import {sharedFooter} from './shared-footer.js';
import {diagnosticWidget} from './diagnostic.js';
import {projectVisual,projectImage,subsifyGallery} from './project-media.js';
import {languageAlternates,pageDescription,socialMetadata,robotsMeta,type SEOEnvironment} from './seo-policy.js';
import {navigationItems,footerNavigationItems,isCurrentPage} from './navigation.js';
import {escapeHTML as esc} from './catalog.js';
import {art as draw} from './art.js';
import {bi,localPath,langSwitch,type Locale,type Bilingual} from './i18n.js';
import {company,serviceContent,marketedServices,caseStudies,industryContent,editorial,method,faqContent,type ContentItem,type CaseStudy,type Post,type Feature} from './content.js';
export interface Page {path:string;title:string;family:string;body:string;description?:string;}
import {logo} from './brand.js';
export {logo} from './brand.js';
export const canonicalPath=(path:string):string=>path==='/'?'/':path.replace(/\/$/,'');
export function renderer(locale:Locale,environment:SEOEnvironment='preview'){
 const x=(es:string,en:string):string=>locale==='es'?es:en;
 const tr=(s:Bilingual):string=>s[locale];
 const url=(p:string):string=>localPath(p,locale);
 const art=(kind='web',label='PixelTEC'):string=>draw(kind,label,locale);
 const serviceDetailArt=(s:ContentItem):string=>['automation','web','consulting'].includes(s.id)?`<div class="service-detail-visual"><img src="/assets/services/${s.id}-3d-1280.webp" srcset="/assets/services/${s.id}-3d-640.webp 640w, /assets/services/${s.id}-3d-1280.webp 1280w" sizes="(max-width:800px) 90vw, 55vw" width="1280" height="800" alt="${esc(tr(s.title))}" loading="lazy" decoding="async"></div>`:`<div class="service-art">${art(s.visual)}</div>`;
 const arrow='<span aria-hidden="true">↗</span>';
 const link=(label:string,path:string,cls='button'):string=>`<a class="${cls}" href="${url(path)}">${label}${arrow}</a>`;
 const num=(i:number):string=>String(i+1).padStart(2,'0');
 const nav=navigationItems(locale);
 const cta=():string=>`<section class="cta-section wrap"><div><p class="eyebrow">${x('EL SIGUIENTE PASO','YOUR NEXT STEP')}</p><h2>${x('Hablemos de<br><em>tu operación.</em>','Let’s talk about<br><em>your business.</em>')}</h2><p>${x('Un diagnóstico para entender el reto y decidir qué construir primero.','An assessment to understand the challenge and decide what to build first.')}</p></div>${link(x('Iniciar diagnóstico','Start an assessment'),'/diagnostico/')}</section>`;
 const heading=(eyebrow:string,title:string,path?:string):string=>`<div class="section-head"><div><p class="eyebrow">${eyebrow}</p><h2>${title}</h2></div>${path?link(x('Explorar','Explore'),path,'text-link'):''}</div>`;
 const hero=(kicker:string,title:string,description:string,detail=false):string=>`<section class="page-hero ${detail?'hero-detail':''}"><div class="wrap"><div class="breadcrumb"><a href="${url('/')}">${x('Inicio','Home')}</a><span>/</span><span>${kicker}</span></div><div class="hero-overline"><span class="eyebrow">${kicker}</span><span class="spark" aria-hidden="true">✳</span></div><h1>${title}</h1><div class="hero-bottom"><p>${description}</p><a class="round-link" href="#contenido" aria-label="${x('Explorar contenido','Explore content')}">↓</a></div></div></section>`;
 const features=(items:Feature[]):string=>`<div class="feature-grid">${items.map((f,i)=>`<article><span class="feature-symbol" aria-hidden="true">${['↗','⌘','◎'][i%3]}</span><span class="eyebrow">${num(i)}</span><h3>${tr(f.title)}</h3><p>${tr(f.body)}</p></article>`).join('')}</div>`;
 const process=():string=>`<section class="section dark rounded"><div class="wrap">${heading(x('CÓMO TRABAJAMOS','HOW WE WORK'),x('Primero entender.<br>Después construir.','Understand first.<br>Then build.'),'/metodologia/')}<div class="process-grid">${method.map((f,i)=>`<article><span class="step-no">${num(i)}</span><h3>${tr(f.title)}</h3><p>${tr(f.body)}</p></article>`).join('')}</div></div></section>`;
 const faq=():string=>`<section class="section wrap faq-layout">${heading(x('PREGUNTAS FRECUENTES','FREQUENTLY ASKED QUESTIONS'),x('Decide con<br>claridad.','Decide with<br>clarity.'))}<div>${faqContent.map((f,i)=>`<details ${i===0?'open':''}><summary><span>${num(i)}</span>${tr(f.title)}<b>+</b></summary><p>${tr(f.body)}</p></details>`).join('')}</div></section>`;
 const caseCards=(items=caseStudies):string=>`<div class="cards project-cards">${items.map((c,i)=>`<article class="work-card" data-category="${tr(c.category)}" data-search="${esc(c.name.toLowerCase())}"><a href="${url(c.path)}" class="visual-link" aria-label="${x('Ver proyecto','View project')} ${c.name}">${projectVisual(c,locale)}<span class="card-arrow">↗</span></a><div class="card-meta"><span>${num(i)} / ${tr(c.category)}</span><span>${x('PROYECTO','PROJECT')}</span></div><h3><a href="${url(c.path)}">${c.name}</a></h3><p class="card-description">${tr(c.description)}</p></article>`).join('')}</div>`;
 const filters=(labels:string[]):string=>`<div class="filters" role="group" aria-label="${x('Filtrar resultados','Filter results')}">${[x('Todos','All'),...labels].map((v,i)=>`<button data-filter="${v}" aria-pressed="${i===0}">${v}</button>`).join('')}</div>`;
 const date=(v:string):string=>new Intl.DateTimeFormat(locale==='es'?'es-MX':'en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(v+'T12:00:00Z'));
 const postCards=(items=editorial):string=>`<div class="cards blog-cards">${items.map(p=>`<article class="work-card" data-category="${tr(p.category)}" data-search="${esc(tr(p.title).toLocaleLowerCase(locale))}"><a href="${url(p.path)}" class="visual-link" aria-label="${esc(tr(p.title))}">${art(p.visual)}<span class="card-arrow">↗</span></a><div class="card-meta"><span>${tr(p.category)}</span><span>${date(p.date)}</span></div><h3><a href="${url(p.path)}">${tr(p.title)}</a></h3><p class="card-description">${tr(p.description)}</p></article>`).join('')}</div>`;
 function header(path:string):string{return `<a class="skip-link" href="#main">${x('Saltar al contenido','Skip to content')}</a><div class="header-shell"><header class="site-header"><nav class="site-primary-nav" aria-label="${x('Navegación principal','Main navigation')}">${nav.map(([t,h])=>`<a ${isCurrentPage(path,h!)?'aria-current="page"':''} href="${url(h!)}">${t}.</a>`).join('')}</nav><a class="brand" href="${url('/')}" aria-label="${x('PixelTEC Inicio','PixelTEC Home')}">${logo}PixelTEC</a><div class="header-end"><div class="header-social"><a href="https://www.facebook.com/profile.php?id=61556300117500" aria-label="Facebook">FB.</a><a href="https://instagram.com/pixeltecmx" aria-label="Instagram">IG.</a><a href="${company.whatsapp}" aria-label="WhatsApp">WA.</a></div><a class="talk" href="${url('/contact/')}">${x('Hablemos','Let’s talk')}</a>${langSwitch(path,locale)}<button class="menu-toggle" aria-label="${x('Abrir menú','Open menu')}" aria-controls="site-menu" aria-expanded="false"><span></span><span></span><span></span></button></div></header></div><dialog id="site-menu" class="menu-dialog"><div class="menu-top"><a class="brand" href="${url('/')}">${logo}PixelTEC</a><button data-close-menu aria-label="${x('Cerrar menú','Close menu')}">×</button></div><div class="menu-grid"><nav aria-label="${x('Todas las páginas','All pages')}">${nav.map(([t,h],i)=>`<a href="${url(h!)}"><small>${num(i)}</small>${t}${arrow}</a>`).join('')}</nav><div><p class="eyebrow">${x('DE LA IDEA A LA ACCIÓN','FROM IDEA TO ACTION')}</p><p class="menu-heading">${x('Tecnología con<br>un propósito:<br>tu negocio.','Technology with<br>a purpose:<br>your business.')}</p>${link(x('Iniciar diagnóstico','Start an assessment'),'/diagnostico/')}<div class="menu-extra">${[[x('Proyectos','Work'),'/proyectos/'],[x('Equipo','Team'),'/equipo/'],[x('Metodología','Our process'),'/metodologia/'],[x('Guías y ciudades','Guides & cities'),'/guias-transformacion/'],[x('Acceso de clientes','Client access'),'/login/']].map(([t,h])=>`<a href="${url(h!)}">${t} ↗</a>`).join('')}</div>${langSwitch(path,locale)}<small>PUERTO VALLARTA · ${x('MÉXICO','MEXICO')}</small></div></div></dialog>`;}
 function footer():string{return sharedFooter(locale); }
 function serviceIndex():string{return hero(x('LO QUE HACEMOS','WHAT WE DO'),x('Tecnología que<br><em>trabaja contigo.</em>','Technology that<br><em>works with you.</em>'),x('Desarrollamos tecnología a la medida para modernizar la logística, operación y presencia digital de tu empresa.','We build custom technology to modernize your logistics, operations and digital presence.'))+`<section class="section wrap" id="contenido"><div class="service-list">${marketedServices.map((s,i)=>`<article class="service-row"><span class="eyebrow">${num(i)}</span><div><h2><a href="${url(s.path)}">${tr(s.title)}</a></h2><p>${tr(s.description)}</p><div class="tags">${tr(s.category).split(' · ').map(t=>`<span>${t}</span>`).join('')}</div>${link(x('Explorar servicio','Explore service'),s.path,'text-link')}</div><a class="service-art" href="${url(s.path)}" aria-label="${esc(tr(s.title))}">${art(s.visual)}</a></article>`).join('')}</div></section>`+process()+faq()+cta();}
 function serviceDetail(s:ContentItem,kicker=x('SERVICIOS','SERVICES')):string{return hero(kicker,tr(s.title),tr(s.description),true)+`<section class="wrap detail-intro" id="contenido"><div class="detail-art">${serviceDetailArt(s)}</div><div class="detail-sidebar"><p class="eyebrow">${x('EL PUNTO DE PARTIDA','THE STARTING POINT')}</p><h2>${x('Diseñado alrededor<br>de tu operación.','Designed around<br>your operations.')}</h2><p>${tr(s.features[0]?.body??company.description)}</p>${link(x('Hablemos de tu proyecto','Let’s discuss your project'),'/diagnostico/')}<div class="tiny-rule">${tr(s.category)}</div></div></section><section class="section wrap">${heading(x('CAPACIDADES','CAPABILITIES'),x('Cada pieza tiene<br>un propósito.','Every piece has<br>a purpose.'))}${features(s.features)}</section>${s.id==='whatsagent'?whatsAgentExtra():''}`+process()+faq()+cta();}
 function whatsAgentExtra():string{return `<section class="section dark rounded"><div class="wrap">${heading('WHATSAGENT',x('Tu marca.<br>Tus reglas. Tu control.','Your brand.<br>Your rules. Your control.'))}<div class="process-grid">${[bi('Tu cliente escribe','Your customer writes'),bi('Responde y califica','Responds and qualifies'),bi('Conserva contexto','Keeps the context'),bi('Resuelve o transfiere','Resolves or hands over')].map((t,i)=>`<article><span class="step-no">${num(i)}</span><h3>${tr(t)}</h3></article>`).join('')}</div><p class="source-note">${x('API oficial de WhatsApp. Integraciones, capacidad y soporte según el plan y el alcance acordado.','Official WhatsApp API. Integrations, capacity and support depend on the plan and agreed scope.')}</p>${link(x('Consultar planes vigentes','View current plans'),'https://pixeltec.mx/pixelbot','text-link')}</div></section>`;}
 function founder(updated=false):string{return `<div class="founder-card"><img src="/assets/${updated?'miguel-robles-about':'miguel-robles'}.webp" alt="Miguel Robles Sánchez" width="${updated?1122:640}" height="${updated?1402:640}" loading="lazy"><div><p class="eyebrow">${x('FUNDADOR','FOUNDER')}</p><h2>Miguel Robles<br>Sánchez</h2><p class="founder-role">Founder & Lead Software Architect</p><p>${x('Ingeniero de software con experiencia construyendo ecosistemas digitales para empresas mexicanas de logística, salud y retail. Su foco: rentabilidad operativa y control del negocio.','A software engineer with experience building digital ecosystems for Mexican businesses in logistics, healthcare and retail. His focus: operational profitability and business control.')}</p>${link(x('Conversemos','Let’s talk'),'/contact/','text-link')}</div></div>`;}
 function about():string{return hero(x('SOBRE NOSOTROS','ABOUT PIXELTEC'),x('Un aliado.<br><em>De verdad.</em>','A partner.<br><em>Through and through.</em>'),x('Combinamos consultoría empresarial con desarrollo de software de alto nivel para escalar tu ecosistema digital.','We combine business consulting and advanced software development to grow your digital ecosystem.'))+`<section class="wrap about-stage" id="contenido"><div class="about-visual"><span class="eyebrow">${x('PERSONAS + TECNOLOGÍA','PEOPLE + TECHNOLOGY')}</span><img src="/assets/desarrollador-720.webp" alt="${x('Personaje ilustrado de PixelTEC','PixelTEC illustrated character')}" width="720" height="720" loading="lazy"><span class="stage-caption">${x('Criterio humano.<br>Posibilidades digitales.','Human judgment.<br>Digital possibilities.')}</span></div><div class="manifesto"><p class="eyebrow">${x('NUESTRA FORMA DE VERLO','OUR APPROACH')}</p><h2>${x('La tecnología<br>es un medio.<br><em>Tu negocio, el fin.</em>','Technology<br>is the means.<br><em>Your business, the goal.</em>')}</h2><p>${tr(company.about)}</p><p>${tr(company.team)}</p></div></section>`+process()+`<section class="section wrap">${founder(true)}</section>`+cta();}
 function team():string{return hero(x('NUESTRO EQUIPO','OUR TEAM'),x('Criterio humano.<br><em>Trabajo en equipo.</em>','Human judgment.<br><em>Shared expertise.</em>'),tr(company.team))+`<section class="section wrap" id="contenido">${founder()}</section><section class="section dark rounded"><div class="wrap">${heading(x('RED DE COLABORADORES','COLLABORATOR NETWORK'),x('El talento que<br>cada proyecto necesita.','The expertise<br>each project needs.'))}<p class="section-description">${x('Especialistas en diseño, QA, infraestructura y branding se integran según las necesidades técnicas del proyecto.','Specialists in design, quality assurance, infrastructure and branding join according to each project’s technical needs.')}</p><div class="expertise-list">${['UI / UX',x('Calidad y pruebas','Quality & testing'),x('Infraestructura','Infrastructure'),'Branding'].map((t,i)=>`<div><span>${num(i)}</span><h3>${t}</h3><span>↗</span></div>`).join('')}</div></div></section>`+cta();}
 function projectIndex():string{return hero(x('TRABAJO SELECCIONADO','SELECTED WORK'),x('Tecnología.<br><em>En operación.</em>','Technology.<br><em>In action.</em>'),x('Proyectos y experiencias publicados por PixelTEC. Cada caso empieza con una necesidad concreta del negocio.','Projects and experiences published by PixelTEC. Each case starts with a specific business need.'))+`<section class="section wrap" id="contenido">${filters([x('Web','Web'),x('Automatización','Automation'),x('Plataformas','Platforms'),'Apps'])}<h2 class="eyebrow">${x("Proyectos seleccionados","Selected projects")}</h2>${caseCards()}<p class="empty-state" hidden>${x('No hay proyectos en esta categoría.','There are no projects in this category.')}</p><p class="visual-caption">${x('Sitios web, plataformas y apps con la identidad de cada proyecto.','Websites, platforms and apps with each project’s own identity.')}</p></section>`+cta();}
 function projectDetail(c:CaseStudy):string{
  const visualNote=!projectImage(c.id)&&c.id!=='subsify'?`<p class="visual-caption">${x('Representación conceptual de la solución.','Conceptual illustration of the solution.')}</p>`:'';
  const testimonial=c.person&&tr(c.quote)?`<section class="section wrap story-grid"><p class="eyebrow">${x('02 / LA VOZ DEL CLIENTE','02 / THE CLIENT’S EXPERIENCE')}</p><div><blockquote>“${tr(c.quote)}”</blockquote><p><strong>${c.person}</strong><br>${tr(c.role)}</p>${locale==='en'?'<p class="visual-caption">English translation of the published Spanish testimonial.</p>':''}</div></section>`:'';
  return hero(x('PROYECTOS','WORK'),c.name,tr(c.description),true)+`<section class="wrap case-hero" id="contenido">${projectVisual(c,locale,true)}${visualNote}<div class="case-meta"><div><span>${x('PROYECTO','PROJECT')}</span><strong>${c.name}</strong></div><div><span>${x('DISCIPLINA','DISCIPLINE')}</span><strong>${tr(c.category)}</strong></div><div><span>PIXELTEC</span><strong>${x('Diseño y tecnología','Design & technology')}</strong></div></div></section><section class="section wrap story-grid"><p class="eyebrow">${x('01 / LA SOLUCIÓN','01 / THE SOLUTION')}</p><div><h2>${x('Diseñado alrededor<br>de una necesidad.','Designed around<br>a real need.')}</h2><p>${tr(c.scope)}</p></div></section>`+(c.id==='subsify'?subsifyGallery(locale):'')+testimonial+`<section class="wrap next-project">${link(x('Todos los proyectos','All projects'),'/proyectos/','next-title')}</section>`;
 }

 function industryIndex():string{return hero(x('INDUSTRIAS','INDUSTRIES'),x('Entendemos<br><em>tu contexto.</em>','We understand<br><em>your context.</em>'),x('Operamos dentro de industrias reales. Diseñamos a partir de cómo funciona cada negocio.','We work within real industries. We design around how each business operates.'))+`<section class="section wrap" id="contenido"><div class="industry-grid">${industryContent.map((it,i)=>`<article id="${it.id}"><span class="eyebrow">${num(i)} / ${x('INDUSTRIA','INDUSTRY')}</span><h2>${tr(it.title)}</h2><p>${tr(it.description)}</p>${industryArt(it.id,locale)}${link(i<2?x('Explorar industria','Explore industry'):x('Conversemos','Let’s talk'),i<2?it.path:'/diagnostico/','text-link')}</article>`).join('')}</div></section>`+cta();}
 function blogIndex():string{return hero(x('IDEAS / PERSPECTIVAS','IDEAS / PERSPECTIVES'),x('Tecnología práctica.<br><em>Mejores decisiones.</em>','Practical technology.<br><em>Better decisions.</em>'),x('Guías publicadas por PixelTEC sobre automatización, software a la medida e inteligencia artificial.','Guides published by PixelTEC on automation, custom software and artificial intelligence.'))+`<section class="section wrap" id="contenido"><div class="blog-tools">${filters([x('IA','AI'),x('Automatización','Automation'),x('Operación','Operations'),x('Estrategia','Strategy')])}<label class="search"><span class="sr-only">${x('Buscar artículos','Search articles')}</span><input type="search" placeholder="${x('Buscar una idea…','Find an idea…')}" data-search-input><span>⌕</span></label></div><h2 class="eyebrow">${x("Artículos publicados","Published articles")}</h2>${postCards()}<p class="empty-state" hidden>${x('No encontramos artículos. Prueba otra búsqueda.','No articles found. Try another search.')}</p></section>`+cta();}
 function article(p:Post):string{return hero(tr(p.category),tr(p.title),tr(p.description),true)+`<section class="wrap article-cover" id="contenido">${art(p.visual)}</section><section class="section wrap article-layout"><aside><p class="eyebrow">${x('EN ESTA GUÍA','IN THIS GUIDE')}</p>${p.sections.map((s,i)=>`<a href="#idea-${i}">${num(i)} / ${tr(s.title)}</a>`).join('')}<p>${p.author}<br>${date(p.date)}</p></aside><article class="article-copy"><p class="notice">${x('Lectura breve basada en el artículo publicado.','A brief overview based on the published article.')}</p>${p.sections.map((s,i)=>`<h2 id="idea-${i}">${tr(s.title)}</h2><p>${tr(s.body)}</p>`).join('')}${link(x(`Leer artículo completo · ${p.minutes} min`,`Read the full Spanish article · ${p.minutes} min`),'https://pixeltec.mx'+canonicalPath(p.path),'text-link')}</article></section>`+cta();}
 function contact():string{return hero(x('CONVERSEMOS','LET’S TALK'),x('Tu próximo paso<br><em>empieza aquí.</em>','Your next step<br><em>starts here.</em>'),x('Cuéntanos sobre tu desafío operativo o proyecto tecnológico. Desde Puerto Vallarta diseñamos tu próxima solución.','Tell us about your operational challenge or technology project. From Puerto Vallarta, we design your next solution.'))+`<section class="section wrap contact-layout" id="contenido"><div><p class="eyebrow">${x('EL PRIMER CONTACTO','THE FIRST CONVERSATION')}</p><h2>${x('Una conversación.<br>Una dirección clara.','One conversation.<br>A clear direction.')}</h2><img class="contact-mascot" src="/assets/desarrollador-360.webp" alt="${x('Personaje de PixelTEC','PixelTEC character')}" width="360" height="360" loading="lazy"><div class="contact-detail"><span>PUERTO VALLARTA · JALISCO · ${x('MÉXICO','MEXICO')}</span><p><a href="tel:+523221378336">${company.phone}</a><br><a href="mailto:${company.email}">${company.email}</a></p></div></div><div class="contact-form contact-options"><p class="eyebrow">${x('ELIGE CÓMO EMPEZAR','CHOOSE HOW TO START')}</p><h2>${x('Hablemos de<br>lo que necesitas.','Let’s talk about<br>what you need.')}</h2><p>${x('Si ya conoces el reto, escríbenos. Si todavía estás explorando, el diagnóstico te ayuda a ordenar el punto de partida.','If you know the challenge, get in touch. If you are still exploring, the assessment helps organize your starting point.')}</p>${link(x('Escribir por WhatsApp','Message us on WhatsApp'),company.whatsapp)}${link(x('Enviar un correo','Send an email'),'mailto:'+company.email,'button button-outline')}<details class="contact-diagnostic"><summary class="text-link">${x('Iniciar diagnóstico','Start an assessment')} <span aria-hidden="true">↗</span></summary>${diagnosticWidget(locale)}</details><p class="visual-caption">${x('Tú eliges cuándo enviar el mensaje desde WhatsApp o tu aplicación de correo.','You choose when to send your message from WhatsApp or your email app.')}</p></div></section>`+faq();}
 function diagnostic():string{return `<section class="diagnostic-page wrap" id="contenido"><div class="diagnostic-intro"><p class="eyebrow">${x('DIAGNÓSTICO','ASSESSMENT')} / PIXELTEC</p><h1>${x('Entender hoy.<br><em>Decidir mejor.</em>','Understand today.<br><em>Decide better.</em>')}</h1><p>${x('Cuatro preguntas para ordenar el punto de partida de tu negocio.','Four questions to organize your business’s starting point.')}</p>${link(x('Prefiero conversar','I’d rather talk'),'/contact/','text-link')}<div class="diagnostic-note">${x('Tus respuestas permanecen en esta página. Al finalizar puedes compartir el resumen por WhatsApp.','Your answers stay on this page. At the end, you can choose to share the summary on WhatsApp.')}</div></div>${diagnosticWidget(locale)}</section>`;}
 function methodology():string{return hero(x('METODOLOGÍA','OUR PROCESS'),x('La claridad<br><em>marca el camino.</em>','Clarity<br><em>sets the direction.</em>'),x('Un proceso que conecta el diagnóstico, el diseño y el desarrollo con la operación del negocio.','A process connecting assessment, design and development to business operations.'))+`<section class="section wrap" id="contenido"><div class="method-list">${method.map((m,i)=>`<article><span class="method-no">${num(i)}</span><div><p class="eyebrow">${x('ETAPA','STAGE')} ${i+1}</p><h2>${tr(m.title)}</h2><p>${tr(m.body)}</p></div><span class="method-symbol" aria-hidden="true">${['◎','⌘','✳','↗'][i]}</span></article>`).join('')}</div></section>`+faq()+cta();}
 function legal(title:string,sourcePath:string):string{return hero(x('INFORMACIÓN','INFORMATION'),title,x('Consulta la documentación vigente de PixelTEC.','Read PixelTEC’s current documentation.'),true)+`<section class="section wrap article-layout" id="contenido"><aside><p class="eyebrow">PIXELTEC</p><a href="mailto:${company.email}">${company.email}</a></aside><article class="article-copy"><h2>${x('Documento vigente','Current document')}</h2><p>${x('La versión publicada en pixeltec.mx contiene las condiciones e información vigentes. Consulta el documento completo en su fuente original.','The version published on pixeltec.mx contains the current terms and information. Read the complete document in its original Spanish version.')}</p>${link(x('Consultar documento completo','Read the full Spanish document'),'https://pixeltec.mx'+canonicalPath(sourcePath))}<p>${x('Los enlaces de contacto te permiten comunicarte directamente con PixelTEC por WhatsApp o correo electrónico.','Contact PixelTEC directly through the WhatsApp and email links provided.')}</p></article></section>`;}
 function auth(reset=false):string{return hero(x('CLIENTES','CLIENTS'),x('El espacio<br><em>de tu proyecto.</em>','Your project.<br><em>Your space.</em>'),x('Accede al portal existente de PixelTEC.','Access the existing PixelTEC portal.'))+`<section class="section wrap" id="contenido"><div class="portal-card">${art('grid')}<div><p class="eyebrow">PIXELTEC / ${x('ACCESO SEGURO','SECURE ACCESS')}</p><h2>${reset?x('Recupera tu acceso.','Recover your access.'):x('Sigamos conectados.','Let’s stay connected.')}</h2><p>${x('El acceso y la recuperación se realizan en el portal oficial. Aquí no solicitamos ni guardamos contraseñas.','Sign-in and recovery take place on the official portal. We do not request or store passwords here.')}</p>${link(reset?x('Ir a recuperación','Recover access'):x('Ir al portal de clientes','Open client portal'),'https://pixeltec.mx'+(reset?'/reset-password':'/login'))}</div></div></section>`;}
 function notFound():string{return `<section class="not-found wrap" id="contenido"><p class="eyebrow">${x('UN PEQUEÑO DESVÍO','A SMALL DETOUR')}</p><h1>4<span>✳</span>4</h1><h2>${x('Esta página está<br>fuera del mapa.','This page is<br>off the map.')}</h2><p>${x('Volvamos a un buen punto de partida.','Let’s return to a good starting point.')}</p>${link(x('Volver al inicio','Back to home'),'/')}</section>`;}
 function directory(entries:{path:string;title:string;family:string}[],map=false):string{return hero(map?x('MAPA DEL SITIO','SITEMAP'):x('GUÍAS Y PRESENCIA LOCAL','GUIDES & LOCAL PRESENCE'),map?x('Todo<br><em>conectado.</em>','Everything<br><em>connected.</em>'):x('Cerca de ti.<br><em>Dentro de tu operación.</em>','Close to you.<br><em>Inside your business.</em>'),tr(company.tagline))+`<section class="section wrap" id="contenido">${[...new Set(entries.map(e=>e.family))].map(f=>`<section class="directory-group"><h2>${f}</h2><div>${entries.filter(e=>e.family===f).map(e=>`<a href="${url(e.path)}"><span>${esc(e.title)}</span>${arrow}</a>`).join('')}</div></section>`).join('')}</section>`;}
 function guide(s:ContentItem,originalBlocks:{tag:string;text:string}[]=[]):string{return hero(x('GUÍAS Y PRESENCIA LOCAL','GUIDES & LOCAL PRESENCE'),tr(s.title),tr(s.description),true)+`<section class="section wrap article-layout" id="contenido"><aside><p class="eyebrow">PIXELTEC</p>${link(x('Iniciar diagnóstico','Start an assessment'),'/diagnostico/','text-link')}${link(x('Consultar servicios','Explore services'),'/services/','text-link')}</aside><article class="article-copy">${locale==='es'&&originalBlocks.length?originalBlocks.map(b=>b.tag==='H2'?`<h2>${esc(b.text)}</h2>`:b.tag==='H3'?`<h3>${esc(b.text)}</h3>`:`<p>${esc(b.text)}</p>`).join(''):`<p class="lead">${tr(s.description)}</p><p class="notice">An English overview of PixelTEC’s published Spanish guide.</p>${s.features.map(f=>`<h2>${tr(f.title)}</h2><p>${tr(f.body)}</p>`).join('')}`}${link(x('Consultar publicación original','Read the full Spanish guide'),s.source,'text-link')}</article></section>`+cta();}
 function document(page:Page):string{const path=url(page.path);const desc=page.description??pageDescription(page.body,page.title,locale);const alternates=languageAlternates(page.path);return `<!doctype html><html lang="${locale==='es'?'es-MX':'en'}" id="top"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">${robotsMeta(page.path,locale,environment)}<title>${esc(page.title)} | PixelTEC</title><meta name="description" content="${esc(desc)}"><link rel="canonical" href="https://pixeltec.mx${canonicalPath(path)}">${alternates}${socialMetadata(page.title+" | PixelTEC",desc,path,locale)}<link rel="icon" href="/favicon.svg"><link rel="preload" href="/fonts/bricolage.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/fonts.css"><link rel="stylesheet" href="/shell.css"><link rel="stylesheet" href="/content.css"><link rel="stylesheet" href="/motion.css">${page.body.includes('service-art')?'<link rel="stylesheet" href="/service-motion.css">':''}${page.body.includes('sector-art')?'<link rel="stylesheet" href="/industry-art.css">':''}<link rel="stylesheet" href="/navigation.css"><script defer src="/app-navigation.js"></script><script type="module" src="/client.js"></script></head><body>${header(page.path)}<main id="main">${page.body}</main>${footer()}</body></html>`;}
 return {document,serviceIndex,serviceDetail,about,team,projectIndex,projectDetail,industryIndex,blogIndex,article,contact,diagnostic,methodology,legal,auth,notFound,directory,guide};
}
